{% set name = "getdaft" %}
{% set version = "0.2.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Eventual-Inc/Daft/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3e637a2702ad7c43d95f1d3a116e686eb487c68dcfc4a063bd83c61f317bf04

build:
  skip: true  # [py<37]
  script:
    - set OPENSSL_DIR=%LIBRARY_PREFIX%  # [win]
    - set OPENSSL_NO_VENDOR=1  # [win]
    - export OPENSSL_DIR=${PREFIX}  # [unix]
    - export OPENSSL_NO_VENDOR=1  # [unix]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }} 1.79.0.dev20240401
    - pkg-config
    - make
  host:
    - python
    - maturin >=1.2.0,<1.3.0
    - pip
    - openssl
    - xz
  run:
    - python
    - pyarrow >=7.0.0
    - fsspec
    - tqdm
    - typing-extensions >=4.0.0  # [py<310]
    - pickle5 >=0.0.12  # [py<38]

test:
  imports:
    - daft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.getdaft.io/
  dev_url: https://github.com/Eventual-Inc/Daft
  doc_url: https://www.getdaft.io/projects/docs/
  summary: Distributed Dataframes for Multimodal Data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
