{% set name = "getdaft" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Eventual-Inc/Daft/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 035dc9957937894f25f2078e5d177239d669be3a4caefc034042818329210b17

build:
  skip: true  # [py<38]
  script:
    - set OPENSSL_DIR=%LIBRARY_PREFIX%  # [win]
    - set OPENSSL_NO_VENDOR=1  # [win]
    - export OPENSSL_DIR=${PREFIX}  # [unix]
    - export OPENSSL_NO_VENDOR=1  # [unix]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - pkg-config
    - make
  host:
    - python
    - maturin >=1.5.0,<2.0.0
    - pip
    - openssl
    - xz-tools
  run:
    - python
    - pyarrow >=7.0.0
    - fsspec
    - tqdm
    - typing-extensions >=4.0.0  # [py<310]

test:
  imports:
    - daft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.getdaft.io/
  dev_url: https://github.com/Eventual-Inc/Daft
  doc_url: https://www.getdaft.io/projects/docs/
  summary: Distributed Dataframes for Multimodal Data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
